import React, { useState, useEffect, Component } from "react";
import { useNavigate } from "react-router-dom";
import SeatPicker from "react-seat-picker";
import Tooltip from "react-tooltip";
import Calendar from 'react-calendar';
import 'react-calendar/dist/Calendar.css';



// import Final from "./Final";
import "./Seats.css";
function Seatbooking() {
  const [selected, setSelected] = useState([]);
  const [showItem, setShowItem] = useState(false);
  let navigate = useNavigate();
  const rows = [
  //A
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 1, number: "1" },
      { id: 2, number: "2" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
    //B
    [
    null
    ],
    //C
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 3, number: "3", isReserved: true, tooltip: "Andrei Cristescu" },
      { id: 4, number: "4" },
      null,
      null,
      null,
      { id: 5, number: "5" },
      { id: 6, number: "6" },
      { id: 7, number: "7" },
      { id: 8, number: "8" },
      { id: 9, number: "9" },
      { id: 10, number: "10" },
      null,
      null,
      null,
      null
    ],
    //D
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 11, number: "11" },
      { id: 12, number: "12" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    //E
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 13, number: "13" },
      { id: 14, number: "14" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 15, number: "15" },
      { id: 16, number: "16" },
      null,
      { id: 17, number: "17" },
      { id: 18, number: "18" },
      null,
    ],
    //F
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 19, number: "19" },
      { id: 20, number: "20" },
      null,
      { id: 21, number: "21" },
      { id: 22, number: "22" },
      null
    ],
    //G
    [
      null
    ],
    //H
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 23, number: "23" },
      { id: 24, number: "24" },
      { id: 25, number: "25" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 26, number: "26" },
      { id: 27, number: "27" },
      null,
      { id: 28, number: "28" },
      { id: 29, number: "29" },
      null,
    ],
    //I
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 30, number: "30" },
      { id: 31, number: "31" },
      { id: 32, number: "32" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 33, number: "33" },
      { id: 34, number: "34" },
      null,
      { id: 35, number: "35" },
      { id: 36, number: "36" },
      null,
    ],
    //J
    [
      null
    ],
    //K
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 37, number: "37" },
      null,
      { id: 38, number: "38" },
      { id: 39, number: "39" },
      null,
    ],
    //L
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 40, number: "40" },
      null,
      { id: 41, number: "41" },
      { id: 42, number: "42" },
      null,
    ],
    //M
    [
      null
    ],
    //N
    [
      null,
      null,
      null,
      null,
      null,
      { id: 43, number: "43" },
      { id: 44, number: "44" },
      null,
      { id: 45, number: "45" },
      { id: 46, number: "46" },
      null,
      { id: 47, number: "47" },
      { id: 48, number: "48" },
      null,
      null,
      { id: 49, number: "49" },
      { id: 50, number: "50" },
      null
    ],
    //O
    [
      null,
      null,
      { id: 51, number: "51" },
      null,
      null,
      { id: 52, number: "52" },
      { id: 53, number: "53" },
      null,
      { id: 54, number: "54" },
      { id: 55, number: "55" },
      null,
      { id: 56, number: "56" },
      { id: 57, number: "57" },
      null,
      null,
      { id: 58, number: "58" },
      { id: 59, number: "59" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 60, number: "60" },
      null,
      { id: 61, number: "61" },
      { id: 62, number: "62" },
      null
    ],
    //P
    [
      null,
      null,
      { id: 63, number: "63" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 64, number: "64" },
      null,
      { id: 65, number: "65" },
      { id: 66, number: "66" },
      null
    ],
    //Q
    [
      { id: 67, number: "67" },
      { id: 68, number: "68" },
      null,
      { id: 69, number: "69" },
      null,
      { id: 70, number: "70" },
      { id: 71, number: "71" },
      null,
      { id: 72, number: "72" },
      { id: 73, number: "73" },
      null,
      { id: 74, number: "74" },
      { id: 75, number: "75" },
      null,
      null,
      { id: 76, number: "76" },
      { id: 77, number: "77" },
      null
    ],
    //R
    [
      { id: 78, number: "78" },
      { id: 79, number: "79" },
      null,
      { id: 80, number: "80" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 81, number: "81" },
      null,
      { id: 82, number: "82" },
      { id: 83, number: "83" },
      null
    ],
    //S
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 84, number: "84" },
      null,
      { id: 85, number: "85" },
      { id: 86, number: "86" },
      null
    ],
    //T
    [
      null
    ],
    //U
    [
      { id: 87, number: "87" },
      { id: 88, number: "88" },
      null,
      { id: 89, number: "89" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 90, number: "90" },
      null,
      { id: 91, number: "91" },
      { id: 92, number: "92" },
      null
    ],
    //V
    [
      { id: 93, number: "93" },
      { id: 94, number: "94" },
      null,
      { id: 95, number: "95" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 96, number: "96" },
      null,
      { id: 97, number: "97" },
      { id: 98, number: "98" },
      null
    ],
    //W
    [
      null
    ],
    //X
    [
      { id: 99, number: "99" },
      { id: 100, number: "100" },
      null,
      { id: 101, number: "101" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 102, number: "102" },
      null,
      null,
      null,
      null
    ],
    //Y
    [
      { id: 103, number: "103" },
      { id: 104, number: "104" },
      null,
      { id: 105, number: "105" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 106, number: "106" },
      null,
      null,
      null,
      null
    ],
    //Z
    [
      null
    ],
    // [
    [
      null
    ],
    //  \
    [
      null
    ],
    // ]
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 107, number: "107" },
      { id: 108, number: "108" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 109, number: "109" },
      { id: 110, number: "110" },
      null,
      null,
      null,
      null,
      { id: 111, number: "111" },
      { id: 112, number: "112" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 113, number: "113" },
      { id: 114, number: "114" },
      null
    ],
    // ^
    [
      null
    ],
    // _________
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 115, number: "115" },
      { id: 116, number: "116" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 117, number: "117" },
      { id: 118, number: "118" },
      null,
      null,
      null,
      null,
      { id: 119, number: "119" },
      { id: 120, number: "120" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 121, number: "121" },
      { id: 122, number: "122" },
      null
    ],
    // ``````
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 123, number: "123" },
      { id: 124, number: "124" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 125, number: "125" },
      { id: 126, number: "126" },
      null,
      null,
      null,
      null,
      { id: 127, number: "127" },
      { id: 128, number: "128" },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      { id: 129, number: "129" },
      { id: 130, number: "130" },
      null
    ]
  ];
  const price = 30;
  const totalprice = price * selected.length;
  const addSeatCallback = ({ row, number, id }, addCb) => {
    setSelected((prevItems) => [...prevItems, number]);
    const newtooltip = `tooltip for id-${id} added by callback`;
    addCb(row, number, id, newtooltip);
  };

  const removeSeatCallback = ({ row, number, id }, removeCb) => {
    setSelected((list) => list.filter((item) => item !== number));
    removeCb(row, number);
  };
  
  return (
    <div className="container">
      <div className="seats">
        <h5 className="seat_price"></h5>
        <SeatPicker
          addSeatCallback={addSeatCallback}
          removeSeatCallback={removeSeatCallback}
          rows={rows}
          alpha
          maxReservableSeats={10}
          visible
        />
    </div>
    <div className="sidebar">
      <div className="calendar-container">
        <Calendar />
      </div>
      {selected.length !== 0 ? (
        <>
          <div className="seat-price">
            <div className="seat-select">
              <h1 className="seats-select">SEAT:{selected.toString()}</h1>
            </div>
            <div className="totalprice">
              <h1 className="price">
                price:{"$"}
                {totalprice}
              </h1>
            </div>
          </div>
          <button
            className="continue"
            onClick={() => navigate(`/Final/${selected}/${totalprice}`)}
          >
            continue
          </button>
        </>
      ) : null}
      </div>
     </div>
    );
}

export { Seatbooking };
